"""Add last checkpoint 2

Revision ID: 27d5fdbdbe17
Revises: ac5257f832e1
Create Date: 2019-07-17 08:59:56.181740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d5fdbdbe17'
down_revision = 'ac5257f832e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkpoint', 'source',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('checkpoint', 'source',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
