"""Add checkpoints 2

Revision ID: 968b0b888b04
Revises: b5dd5e65e203
Create Date: 2019-07-12 09:04:46.750348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '968b0b888b04'
down_revision = 'b5dd5e65e203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('odds', 'checkpoint_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('odds', 'place',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('odds', 'win',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('odds', 'value')
    op.drop_column('odds', 'date_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odds', sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('odds', sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('odds', 'win',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('odds', 'place',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('odds', 'checkpoint_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
