"""Add last checkpoint

Revision ID: ac5257f832e1
Revises: 968b0b888b04
Create Date: 2019-07-17 08:56:48.335670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5257f832e1'
down_revision = '968b0b888b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkpoint', sa.Column('source', sa.String(), nullable=True))
    op.add_column('event', sa.Column('last_checkpoint_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'checkpoint', ['last_checkpoint_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'last_checkpoint_id')
    op.drop_column('checkpoint', 'source')
    # ### end Alembic commands ###
